const locator = require('../bluestone-locator.js');
const projectFunc = require('../bluestone-func.js');
const puppeteer = require('puppeteer');
const bluestoneFunc = require('bluestone/ptLibrary/bluestone-func');
const config = require('../config.js');
const bluestoneType = require('bluestone/ptLibrary/class/index');
describe('Account Menu', () => {
    it('should add new address', async function () {
        let element, vars, frame;
        const browser = await puppeteer.launch(config.puppeteer);
        const page = await browser.newPage();
        vars = new bluestoneType.VarSaver(__filename, this.runnable().currentRetry());
        frame = page;
        await bluestoneFunc.initialize.func(vars, page);
        await bluestoneFunc.goto.func(frame, 'https://juice-shop-od.herokuapp.com/#/');
        await bluestoneFunc.waitElementExists.func(frame, locator['dismissBtn'], 1326084, vars.getSnapshot('Bluestone-Snapshot-1'));
        await bluestoneFunc.click.func(frame, locator['dismissBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['accountTab'], 3000, vars.getSnapshot('Bluestone-Snapshot-3'));
        await bluestoneFunc.click.func(frame, locator['accountTab']);
        await bluestoneFunc.waitElementExists.func(frame, locator['loginBtn'], 3000, vars.getSnapshot('Bluestone-Snapshot-5'));
        await bluestoneFunc.click.func(frame, locator['loginBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['emailBox'], 3000, vars.getSnapshot('Bluestone-Snapshot-7'));
        await bluestoneFunc.click.func(frame, locator['emailBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['emailBox'], 7571, vars.getSnapshot('Bluestone-Snapshot-9'));
        await bluestoneFunc.change.func(frame, locator['emailBox'], 'birsen@gmail.com');
        await bluestoneFunc.waitElementExists.func(frame, locator['passwordBox'], 3000, vars.getSnapshot('Bluestone-Snapshot-11'));
        await bluestoneFunc.click.func(frame, locator['passwordBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['passwordBox'], 4315, vars.getSnapshot('Bluestone-Snapshot-13'));
        await bluestoneFunc.change.func(frame, locator['passwordBox'], '12345');
        await bluestoneFunc.waitElementExists.func(frame, locator['signInBtn'], 3000, vars.getSnapshot('Bluestone-Snapshot-15'));
        await bluestoneFunc.click.func(frame, locator['signInBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['accountTab'], 30456, vars.getSnapshot('Bluestone-Snapshot-17'));
        await bluestoneFunc.click.func(frame, locator['accountTab']);
        await bluestoneFunc.waitElementExists.func(frame, locator['orderPaymentsTab'], 11548, vars.getSnapshot('Bluestone-Snapshot-19'));
        await bluestoneFunc.hover.func(frame, locator['orderPaymentsTab']);
        await bluestoneFunc.waitElementExists.func(frame, locator['mySavedAddress'], 31954, vars.getSnapshot('Bluestone-Snapshot-21'));
        await bluestoneFunc.click.func(frame, locator['mySavedAddress']);
        await bluestoneFunc.waitElementExists.func(frame, locator['addNewAddressBtn'], 6172, vars.getSnapshot('Bluestone-Snapshot-23'));
        await bluestoneFunc.testTextEqual.func(frame, locator['addNewAddressBtn'], 'Add New Address');
        await bluestoneFunc.waitElementExists.func(frame, locator['addNewAddressBtn'], 11097, vars.getSnapshot('Bluestone-Snapshot-25'));
        await bluestoneFunc.click.func(frame, locator['addNewAddressBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['countryBox'], 368915, vars.getSnapshot('Bluestone-Snapshot-27'));
        await bluestoneFunc.click.func(frame, locator['countryBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['countryBox'], 7469, vars.getSnapshot('Bluestone-Snapshot-29'));
        await bluestoneFunc.change.func(frame, locator['countryBox'], 'United states');
        await bluestoneFunc.waitElementExists.func(frame, locator['nameBox'], 3000, vars.getSnapshot('Bluestone-Snapshot-31'));
        await bluestoneFunc.click.func(frame, locator['nameBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['nameBox'], 3000, vars.getSnapshot('Bluestone-Snapshot-33'));
        await bluestoneFunc.click.func(frame, locator['nameBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['nameBox'], 3000, vars.getSnapshot('Bluestone-Snapshot-35'));
        await bluestoneFunc.click.func(frame, locator['nameBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['nameBox'], 3000, vars.getSnapshot('Bluestone-Snapshot-37'));
        await bluestoneFunc.click.func(frame, locator['nameBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['nameBox'], 19752, vars.getSnapshot('Bluestone-Snapshot-39'));
        await bluestoneFunc.change.func(frame, locator['nameBox'], 'Residential  Address');
        await bluestoneFunc.waitElementExists.func(frame, locator['mobilePhoneNumber'], 3000, vars.getSnapshot('Bluestone-Snapshot-41'));
        await bluestoneFunc.click.func(frame, locator['mobilePhoneNumber']);
        await bluestoneFunc.waitElementExists.func(frame, locator['mobilePhoneNumber'], 7419, vars.getSnapshot('Bluestone-Snapshot-43'));
        await bluestoneFunc.change.func(frame, locator['mobilePhoneNumber'], '4567329987');
        await bluestoneFunc.waitElementExists.func(frame, locator['zipCode'], 3000, vars.getSnapshot('Bluestone-Snapshot-45'));
        await bluestoneFunc.click.func(frame, locator['zipCode']);
        await bluestoneFunc.waitElementExists.func(frame, locator['zipCode'], 6943, vars.getSnapshot('Bluestone-Snapshot-47'));
        await bluestoneFunc.change.func(frame, locator['zipCode'], '12345');
        await bluestoneFunc.waitElementExists.func(frame, locator['addressInputBox'], 3000, vars.getSnapshot('Bluestone-Snapshot-49'));
        await bluestoneFunc.click.func(frame, locator['addressInputBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['addressInputBox'], 9833, vars.getSnapshot('Bluestone-Snapshot-51'));
        await bluestoneFunc.change.func(frame, locator['addressInputBox'], '987 Main street');
        await bluestoneFunc.waitElementExists.func(frame, locator['cityInputBox'], 3000, vars.getSnapshot('Bluestone-Snapshot-53'));
        await bluestoneFunc.click.func(frame, locator['cityInputBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['cityInputBox'], 3610, vars.getSnapshot('Bluestone-Snapshot-55'));
        await bluestoneFunc.change.func(frame, locator['cityInputBox'], 'Dallas');
        await bluestoneFunc.waitElementExists.func(frame, locator['stateInputBox'], 63133, vars.getSnapshot('Bluestone-Snapshot-57'));
        await bluestoneFunc.click.func(frame, locator['stateInputBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['stateInputBox'], 12987, vars.getSnapshot('Bluestone-Snapshot-59'));
        await bluestoneFunc.change.func(frame, locator['stateInputBox'], 'Texas');
        await bluestoneFunc.waitElementExists.func(frame, locator['submitAdressBtn'], 3000, vars.getSnapshot('Bluestone-Snapshot-61'));
        await bluestoneFunc.click.func(frame, locator['submitAdressBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['savedAddress'], 25622, vars.getSnapshot('Bluestone-Snapshot-63'));
    }).timeout(100000);

    it('should add new payment method', async function () {
        let element, vars, frame;
        const browser = await puppeteer.launch(config.puppeteer);
        const page = await browser.newPage();
        vars = new bluestoneType.VarSaver(__filename, this.runnable().currentRetry());
        frame = page;
        await bluestoneFunc.initialize.func(vars, page);
        await bluestoneFunc.goto.func(frame, 'https://juice-shop-od.herokuapp.com/#/');
        await bluestoneFunc.waitElementExists.func(frame, locator['dismissBtn'], 61950, vars.getSnapshot('Bluestone-Snapshot-1'));
        await bluestoneFunc.click.func(frame, locator['dismissBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['accountTab'], 6095, vars.getSnapshot('Bluestone-Snapshot-3'));
        await bluestoneFunc.click.func(frame, locator['accountTab']);
        await bluestoneFunc.waitElementExists.func(frame, locator['loginBtn'], 3000, vars.getSnapshot('Bluestone-Snapshot-5'));
        await bluestoneFunc.click.func(frame, locator['loginBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['emailBox'], 3527, vars.getSnapshot('Bluestone-Snapshot-7'));
        await bluestoneFunc.click.func(frame, locator['emailBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['emailBox'], 15115, vars.getSnapshot('Bluestone-Snapshot-9'));
        await bluestoneFunc.change.func(frame, locator['emailBox'], 'birsen@gmail.com');
        await bluestoneFunc.waitElementExists.func(frame, locator['passwordBox'], 3000, vars.getSnapshot('Bluestone-Snapshot-11'));
        await bluestoneFunc.click.func(frame, locator['passwordBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['passwordBox'], 4534, vars.getSnapshot('Bluestone-Snapshot-13'));
        await bluestoneFunc.change.func(frame, locator['passwordBox'], '12345');
        await bluestoneFunc.waitElementExists.func(frame, locator['signInBtn'], 3000, vars.getSnapshot('Bluestone-Snapshot-15'));
        await bluestoneFunc.click.func(frame, locator['signInBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['accountTab'], 11917, vars.getSnapshot('Bluestone-Snapshot-17'));
        await bluestoneFunc.click.func(frame, locator['accountTab']);
        await bluestoneFunc.waitElementExists.func(frame, locator['orderPaymentsTab'], 3576, vars.getSnapshot('Bluestone-Snapshot-19'));
        await bluestoneFunc.hover.func(frame, locator['orderPaymentsTab']);
        await bluestoneFunc.waitElementExists.func(frame, locator['myPaymentOptions'], 46970, vars.getSnapshot('Bluestone-Snapshot-21'));
        await bluestoneFunc.click.func(frame, locator['myPaymentOptions']);
        await bluestoneFunc.waitElementExists.func(frame, locator['paymentOptionText'], 9186, vars.getSnapshot('Bluestone-Snapshot-23'));
        await bluestoneFunc.testTextEqual.func(frame, locator['paymentOptionText'], 'Add a credit or debit card');
        await bluestoneFunc.waitElementExists.func(frame, locator['addNewCard'], 53713, vars.getSnapshot('Bluestone-Snapshot-25'));
        await bluestoneFunc.click.func(frame, locator['addNewCard']);
        await bluestoneFunc.waitElementExists.func(frame, locator['newCardNameBox'], 820142, vars.getSnapshot('Bluestone-Snapshot-27'));
        await bluestoneFunc.click.func(frame, locator['newCardNameBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['newCardNameBox'], 8147, vars.getSnapshot('Bluestone-Snapshot-29'));
        await bluestoneFunc.change.func(frame, locator['newCardNameBox'], 'Chase bank');
        await bluestoneFunc.waitElementExists.func(frame, locator['newCardNumberBox'], 3000, vars.getSnapshot('Bluestone-Snapshot-31'));
        await bluestoneFunc.click.func(frame, locator['newCardNumberBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['newCardNumberBox'], 10004, vars.getSnapshot('Bluestone-Snapshot-33'));
        await bluestoneFunc.change.func(frame, locator['newCardNumberBox'], '1234567887654321');
        await bluestoneFunc.waitElementExists.func(frame, locator['expiryMonth'], 3000, vars.getSnapshot('Bluestone-Snapshot-35'));
        await bluestoneFunc.click.func(frame, locator['expiryMonth']);
        await bluestoneFunc.waitElementExists.func(frame, locator['expiryMonth'], 47866, vars.getSnapshot('Bluestone-Snapshot-37'));
        await bluestoneFunc.click.func(frame, locator['expiryMonth']);
        await bluestoneFunc.waitElementExists.func(frame, locator['expiryMonth'], 8057, vars.getSnapshot('Bluestone-Snapshot-39'));
        await bluestoneFunc.click.func(frame, locator['expiryMonth']);
        await bluestoneFunc.waitElementExists.func(frame, locator['expiryMonth'], 3000, vars.getSnapshot('Bluestone-Snapshot-41'));
        await bluestoneFunc.change.func(frame, locator['expiryMonth'], '2');
        await bluestoneFunc.waitElementExists.func(frame, locator['expiryMonth'], 3000, vars.getSnapshot('Bluestone-Snapshot-43'));
        await bluestoneFunc.click.func(frame, locator['expiryMonth']);
        await bluestoneFunc.waitElementExists.func(frame, locator['expiryYear'], 4634, vars.getSnapshot('Bluestone-Snapshot-45'));
        await bluestoneFunc.click.func(frame, locator['expiryYear']);
        await bluestoneFunc.waitElementExists.func(frame, locator['expiryYear'], 3000, vars.getSnapshot('Bluestone-Snapshot-47'));
        await bluestoneFunc.change.func(frame, locator['expiryYear'], '2082');
        await bluestoneFunc.waitElementExists.func(frame, locator['expiryYear'], 3000, vars.getSnapshot('Bluestone-Snapshot-49'));
        await bluestoneFunc.click.func(frame, locator['expiryYear']);
        await bluestoneFunc.waitElementExists.func(frame, locator['submitAdressBtn'], 51609, vars.getSnapshot('Bluestone-Snapshot-51'));
        await bluestoneFunc.click.func(frame, locator['submitAdressBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['savedBankAccount'], '3000', vars.getSnapshot('Bluestone-Snapshot-53'));
    }).timeout(100000);

    it('should update profile picture', async function () {
        let element, vars, frame;
        const browser = await puppeteer.launch(config.puppeteer);
        const page = await browser.newPage();
        vars = new bluestoneType.VarSaver(__filename, this.runnable().currentRetry());
        frame = page;
        await bluestoneFunc.initialize.func(vars, page);
        await bluestoneFunc.goto.func(frame, 'https://juice-shop-od.herokuapp.com/#/');
        await bluestoneFunc.waitElementExists.func(frame, locator['dismissBtn'], 13291, vars.getSnapshot('Bluestone-Snapshot-1'));
        await bluestoneFunc.click.func(frame, locator['dismissBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['accountTab'], 4233, vars.getSnapshot('Bluestone-Snapshot-3'));
        await bluestoneFunc.click.func(frame, locator['accountTab']);
        await bluestoneFunc.waitElementExists.func(frame, locator['loginBtn'], 3000, vars.getSnapshot('Bluestone-Snapshot-5'));
        await bluestoneFunc.click.func(frame, locator['loginBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['emailBox'], 3286, vars.getSnapshot('Bluestone-Snapshot-7'));
        await bluestoneFunc.click.func(frame, locator['emailBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['emailBox'], 10260, vars.getSnapshot('Bluestone-Snapshot-9'));
        await bluestoneFunc.change.func(frame, locator['emailBox'], 'birsen@gmail.com');
        await bluestoneFunc.waitElementExists.func(frame, locator['passwordBox'], 3000, vars.getSnapshot('Bluestone-Snapshot-11'));
        await bluestoneFunc.click.func(frame, locator['passwordBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['passwordBox'], 6659, vars.getSnapshot('Bluestone-Snapshot-13'));
        await bluestoneFunc.change.func(frame, locator['passwordBox'], '12345');
        await bluestoneFunc.waitElementExists.func(frame, locator['signInBtn'], 3000, vars.getSnapshot('Bluestone-Snapshot-15'));
        await bluestoneFunc.click.func(frame, locator['signInBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['accountTab'], 3000, vars.getSnapshot('Bluestone-Snapshot-17'));
        await bluestoneFunc.click.func(frame, locator['accountTab']);
        await bluestoneFunc.waitElementExists.func(frame, locator['userEmailTab'], 4240, vars.getSnapshot('Bluestone-Snapshot-19'));
        await bluestoneFunc.click.func(frame, locator['userEmailTab']);
        await bluestoneFunc.waitElementExists.func(frame, locator['profileUserName'], 98990, vars.getSnapshot('Bluestone-Snapshot-21'));
        await bluestoneFunc.click.func(frame, locator['profileUserName']);
        await bluestoneFunc.waitElementExists.func(frame, locator['profileUserName'], 3000, vars.getSnapshot('Bluestone-Snapshot-23'));
        await bluestoneFunc.click.func(frame, locator['profileUserName']);
        await bluestoneFunc.waitElementExists.func(frame, locator['profileUserName'], 19978, vars.getSnapshot('Bluestone-Snapshot-25'));
        await bluestoneFunc.change.func(frame, locator['profileUserName'], 'birsenY');
        await bluestoneFunc.waitElementExists.func(frame, locator['setUserNamebtn'], 52589, vars.getSnapshot('Bluestone-Snapshot-27'));
        await bluestoneFunc.click.func(frame, locator['setUserNamebtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['uploadedPicText'], 16507, vars.getSnapshot('Bluestone-Snapshot-29'));
        await bluestoneFunc.upload.func(frame, vars, locator['uploadedPicText'], '..\\data\\should update profile picture\\data\\birsenPhoto.jfif');
        await bluestoneFunc.waitElementExists.func(frame, locator['uploadedPicText'], '3000', vars.getSnapshot('Bluestone-Snapshot-31'));
        await bluestoneFunc.waitElementExists.func(frame, locator['uploadedPictureTab'], 63752, vars.getSnapshot('Bluestone-Snapshot-32'));
        await bluestoneFunc.click.func(frame, locator['uploadedPictureTab']);
    }).timeout(100000);
});