const locator = require('../bluestone-locator.js');
const projectFunc = require('../bluestone-func.js');
const puppeteer = require('puppeteer');
const bluestoneFunc = require('bluestone/ptLibrary/bluestone-func');
const config = require('../config.js');
const bluestoneType = require('bluestone/ptLibrary/class/index');
describe('Home Page', () => {
    it('should browse an item', async function () {
        let element, vars, frame;
        const browser = await puppeteer.launch(config.puppeteer);
        const page = await browser.newPage();
        vars = new bluestoneType.VarSaver(__filename, this.runnable().currentRetry());
        frame = page;
        await bluestoneFunc.initialize.func(vars, page);
        await bluestoneFunc.goto.func(frame, 'https://juice-shop-od.herokuapp.com/#/');
        await bluestoneFunc.waitElementExists.func(frame, locator['dismissBtn'], 7782, vars.getSnapshot('Bluestone-Snapshot-1'));
        await bluestoneFunc.click.func(frame, locator['dismissBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['accountTab'], 6066, vars.getSnapshot('Bluestone-Snapshot-3'));
        await bluestoneFunc.click.func(frame, locator['accountTab']);
        await bluestoneFunc.waitElementExists.func(frame, locator['loginBtn'], 3000, vars.getSnapshot('Bluestone-Snapshot-5'));
        await bluestoneFunc.click.func(frame, locator['loginBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['emailBox'], 3000, vars.getSnapshot('Bluestone-Snapshot-7'));
        await bluestoneFunc.click.func(frame, locator['emailBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['emailBox'], 10633, vars.getSnapshot('Bluestone-Snapshot-9'));
        await bluestoneFunc.change.func(frame, locator['emailBox'], 'birsen@gmail.com');
        await bluestoneFunc.waitElementExists.func(frame, locator['passwordBox'], 3000, vars.getSnapshot('Bluestone-Snapshot-11'));
        await bluestoneFunc.click.func(frame, locator['passwordBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['passwordBox'], 6731, vars.getSnapshot('Bluestone-Snapshot-13'));
        await bluestoneFunc.change.func(frame, locator['passwordBox'], '12345');
        await bluestoneFunc.waitElementExists.func(frame, locator['signInBtn'], 3000, vars.getSnapshot('Bluestone-Snapshot-15'));
        await bluestoneFunc.click.func(frame, locator['signInBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['searchIcon'], 5783, vars.getSnapshot('Bluestone-Snapshot-17'));
        await bluestoneFunc.click.func(frame, locator['searchIcon']);
        await bluestoneFunc.waitElementExists.func(frame, locator['searchIcon'], 24992, vars.getSnapshot('Bluestone-Snapshot-19'));
        await bluestoneFunc.click.func(frame, locator['searchIcon']);
        await bluestoneFunc.waitElementExists.func(frame, locator['searchBox'], 3000, vars.getSnapshot('Bluestone-Snapshot-21'));
        await bluestoneFunc.change.func(frame, locator['searchBox'], 'Orange Juice');
        await bluestoneFunc.keydown.func(frame, 'Enter');
        await bluestoneFunc.waitElementExists.func(frame, locator['searchResult'], 47289, vars.getSnapshot('Bluestone-Snapshot-24'));
        await bluestoneFunc.testTextEqual.func(frame, locator['searchResult'], 'Orange Juice (1000ml)');
    }).timeout(100000);

    it('should change language', async function () {
        let element, vars, frame;
        const browser = await puppeteer.launch(config.puppeteer);
        const page = await browser.newPage();
        vars = new bluestoneType.VarSaver(__filename, this.runnable().currentRetry());
        frame = page;
        await bluestoneFunc.initialize.func(vars, page);
        await bluestoneFunc.goto.func(frame, 'https://juice-shop-od.herokuapp.com/#/');
        await bluestoneFunc.waitElementExists.func(frame, locator['dismissBtn'], 21143, vars.getSnapshot('Bluestone-Snapshot-1'));
        await bluestoneFunc.click.func(frame, locator['dismissBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['languageTab'], 50298, vars.getSnapshot('Bluestone-Snapshot-3'));
        await bluestoneFunc.click.func(frame, locator['languageTab']);
        await bluestoneFunc.waitElementExists.func(frame, locator['deutschLanguage'], 133590, vars.getSnapshot('Bluestone-Snapshot-5'));
        await bluestoneFunc.click.func(frame, locator['deutschLanguage']);
        await bluestoneFunc.waitElementExists.func(frame, locator['productTableTitle'], 14561, vars.getSnapshot('Bluestone-Snapshot-7'));
        await bluestoneFunc.testTextEqual.func(frame, locator['productTableTitle'], 'Alle Produkte');
        await bluestoneFunc.waitElementExists.func(frame, locator['languageTab'], 9401, vars.getSnapshot('Bluestone-Snapshot-9'));
        await bluestoneFunc.click.func(frame, locator['languageTab']);
        await bluestoneFunc.waitElementExists.func(frame, locator['englishLanguage'], 28305, vars.getSnapshot('Bluestone-Snapshot-11'));
        await bluestoneFunc.click.func(frame, locator['englishLanguage']);
    }).timeout(100000);

    it('should logout successfuly', async function () {
        let element, vars, frame;
        const browser = await puppeteer.launch(config.puppeteer);
        const page = await browser.newPage();
        vars = new bluestoneType.VarSaver(__filename, this.runnable().currentRetry());
        frame = page;
        await bluestoneFunc.initialize.func(vars, page);
        await bluestoneFunc.goto.func(frame, 'https://juice-shop-od.herokuapp.com/#/');
        await bluestoneFunc.waitElementExists.func(frame, locator['dismissBtn'], 11150, vars.getSnapshot('Bluestone-Snapshot-1'));
        await bluestoneFunc.click.func(frame, locator['dismissBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['accountTab'], 3070, vars.getSnapshot('Bluestone-Snapshot-3'));
        await bluestoneFunc.click.func(frame, locator['accountTab']);
        await bluestoneFunc.waitElementExists.func(frame, locator['loginBtn'], 3000, vars.getSnapshot('Bluestone-Snapshot-5'));
        await bluestoneFunc.click.func(frame, locator['loginBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['emailBox'], 3000, vars.getSnapshot('Bluestone-Snapshot-7'));
        await bluestoneFunc.click.func(frame, locator['emailBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['emailBox'], 11269, vars.getSnapshot('Bluestone-Snapshot-9'));
        await bluestoneFunc.change.func(frame, locator['emailBox'], 'birsen@gmail.com');
        await bluestoneFunc.waitElementExists.func(frame, locator['passwordBox'], 3000, vars.getSnapshot('Bluestone-Snapshot-11'));
        await bluestoneFunc.click.func(frame, locator['passwordBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['passwordBox'], 4790, vars.getSnapshot('Bluestone-Snapshot-13'));
        await bluestoneFunc.change.func(frame, locator['passwordBox'], '12345');
        await bluestoneFunc.waitElementExists.func(frame, locator['signInBtn'], 3000, vars.getSnapshot('Bluestone-Snapshot-15'));
        await bluestoneFunc.click.func(frame, locator['signInBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['accountTab'], 7520, vars.getSnapshot('Bluestone-Snapshot-17'));
        await bluestoneFunc.click.func(frame, locator['accountTab']);
        await bluestoneFunc.waitElementExists.func(frame, locator['logoutBtn'], 4292, vars.getSnapshot('Bluestone-Snapshot-19'));
        await bluestoneFunc.click.func(frame, locator['logoutBtn']);
    }).timeout(100000);

    it('should paginate on home page', async function () {
        let element, vars, frame;
        const browser = await puppeteer.launch(config.puppeteer);
        const page = await browser.newPage();
        vars = new bluestoneType.VarSaver(__filename, this.runnable().currentRetry());
        frame = page;
        await bluestoneFunc.initialize.func(vars, page);
        await bluestoneFunc.goto.func(frame, 'https://juice-shop-od.herokuapp.com/#/');
        await bluestoneFunc.waitElementExists.func(frame, locator['dismissBtn'], 9785, vars.getSnapshot('Bluestone-Snapshot-1'));
        await bluestoneFunc.click.func(frame, locator['dismissBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['accountTab'], 3000, vars.getSnapshot('Bluestone-Snapshot-3'));
        await bluestoneFunc.click.func(frame, locator['accountTab']);
        await bluestoneFunc.waitElementExists.func(frame, locator['loginBtn'], 3000, vars.getSnapshot('Bluestone-Snapshot-5'));
        await bluestoneFunc.click.func(frame, locator['loginBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['emailBox'], 3000, vars.getSnapshot('Bluestone-Snapshot-7'));
        await bluestoneFunc.click.func(frame, locator['emailBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['emailBox'], 9084, vars.getSnapshot('Bluestone-Snapshot-9'));
        await bluestoneFunc.change.func(frame, locator['emailBox'], 'birsen@gmail.com');
        await bluestoneFunc.waitElementExists.func(frame, locator['passwordBox'], 3000, vars.getSnapshot('Bluestone-Snapshot-11'));
        await bluestoneFunc.click.func(frame, locator['passwordBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['passwordBox'], 4186, vars.getSnapshot('Bluestone-Snapshot-13'));
        await bluestoneFunc.change.func(frame, locator['passwordBox'], '12345');
        await bluestoneFunc.waitElementExists.func(frame, locator['signInBtn'], 3000, vars.getSnapshot('Bluestone-Snapshot-15'));
        await bluestoneFunc.click.func(frame, locator['signInBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['mewantItBtn'], 84643, vars.getSnapshot('Bluestone-Snapshot-17'));
        await bluestoneFunc.click.func(frame, locator['mewantItBtn']);
        await projectFunc.scrollTobottomPage.func(page);
        await bluestoneFunc.waitElementExists.func(frame, locator['defaultPaginationValue'], 9768, vars.getSnapshot('Bluestone-Snapshot-20'));
        await bluestoneFunc.testTextEqual.func(frame, locator['defaultPaginationValue'], '12');
        await bluestoneFunc.waitElementExists.func(frame, locator['paginatorRangeValue'], 58393, vars.getSnapshot('Bluestone-Snapshot-22'));
        await projectFunc.verifyPartialTex.func(frame, locator['paginatorRangeValue'], '36');
        await bluestoneFunc.waitElementExists.func(frame, locator['nextPageArrow'], 114973, vars.getSnapshot('Bluestone-Snapshot-24'));
        await bluestoneFunc.click.func(frame, locator['nextPageArrow']);
        await bluestoneFunc.waitElementExists.func(frame, locator['paginatorRangeValue'], 14354, vars.getSnapshot('Bluestone-Snapshot-26'));
        await projectFunc.verifyPartialTex.func(frame, locator['paginatorRangeValue'], '36');
        await bluestoneFunc.waitElementExists.func(frame, locator['nextPageArrow'], 24901, vars.getSnapshot('Bluestone-Snapshot-28'));
        await bluestoneFunc.click.func(frame, locator['nextPageArrow']);
        await bluestoneFunc.waitElementExists.func(frame, locator['paginatorRangeValue'], 4029, vars.getSnapshot('Bluestone-Snapshot-30'));
        await projectFunc.verifyPartialTex.func(frame, locator['paginatorRangeValue'], '36');
        await bluestoneFunc.waitElementExists.func(frame, locator['previousPageArrow'], 39521, vars.getSnapshot('Bluestone-Snapshot-32'));
        await bluestoneFunc.click.func(frame, locator['previousPageArrow']);
        await bluestoneFunc.waitElementExists.func(frame, locator['previousPageArrow'], 3000, vars.getSnapshot('Bluestone-Snapshot-34'));
        await bluestoneFunc.click.func(frame, locator['previousPageArrow']);
    }).timeout(100000);
});