const locator = require('../bluestone-locator.js');
const projectFunc = require('../bluestone-func.js');
const puppeteer = require('puppeteer');
const bluestoneFunc = require('bluestone/ptLibrary/bluestone-func');
const config = require('../config.js');
const bluestoneType = require('bluestone/ptLibrary/class/index');
describe('Register', () => {
    it('register new user', async function () {
        let element, vars, frame;
        const browser = await puppeteer.launch(config.puppeteer);
        const page = await browser.newPage();
        vars = new bluestoneType.VarSaver(__filename, this.runnable().currentRetry());
        frame = page;
        await bluestoneFunc.initialize.func(vars, page);
        await bluestoneFunc.goto.func(frame, 'https://demoqa.com/login');
        await bluestoneFunc.waitElementExists.func(frame, locator['newUserBtn'], 13796, vars.getSnapshot('Bluestone-Snapshot-1'));
        await bluestoneFunc.click.func(frame, locator['newUserBtn']);
        await bluestoneFunc.waitElementExists.func(frame, locator['newUserNameBx'], 3000, vars.getSnapshot('Bluestone-Snapshot-3'));
        await bluestoneFunc.click.func(frame, locator['newUserNameBx']);
        await bluestoneFunc.waitElementExists.func(frame, locator['newUserNameBx'], 6643, vars.getSnapshot('Bluestone-Snapshot-5'));
        await bluestoneFunc.change.func(frame, locator['newUserNameBx'], 'orhan');
        await bluestoneFunc.waitElementExists.func(frame, locator['newUserPasswordBx'], 3000, vars.getSnapshot('Bluestone-Snapshot-7'));
        await bluestoneFunc.click.func(frame, locator['newUserPasswordBx']);
        await bluestoneFunc.waitElementExists.func(frame, locator['newUserPasswordBx'], 4230, vars.getSnapshot('Bluestone-Snapshot-9'));
        await bluestoneFunc.change.func(frame, locator['newUserPasswordBx'], 'demirci');
        await bluestoneFunc.waitElementExists.func(frame, locator['userNameBox'], 3000, vars.getSnapshot('Bluestone-Snapshot-11'));
        await bluestoneFunc.click.func(frame, locator['userNameBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['userNameBox'], 4436, vars.getSnapshot('Bluestone-Snapshot-13'));
        await bluestoneFunc.change.func(frame, locator['userNameBox'], 'od');
        await bluestoneFunc.waitElementExists.func(frame, locator['passwordBox'], 3000, vars.getSnapshot('Bluestone-Snapshot-15'));
        await bluestoneFunc.click.func(frame, locator['passwordBox']);
        await bluestoneFunc.waitElementExists.func(frame, locator['passwordBox'], 19833, vars.getSnapshot('Bluestone-Snapshot-17'));
        await bluestoneFunc.change.func(frame, locator['passwordBox'], 'O1234567d!-');
        await projectFunc.captcha.func(page, 'recaptcha/api2/anchor');
        await bluestoneFunc.waitElementExists.func(frame, locator['registerBtn'], 4918, vars.getSnapshot('Bluestone-Snapshot-19'));
        await bluestoneFunc.click.func(frame, locator['registerBtn']);
        await bluestoneFunc.waitAndHandleForAlert.func(vars, 2000);
    }).timeout(100000);
});